### PR TITLE
added left padding to My WC card

### PR DESCRIPTION
**Pull request by aagam-shah**

### CODE REVIEW

**Comment by maxme** [comment]
Why you're not reusing `upcoming_wc_card.xml` in `MyWCListAdapter` like in other tabs? Having to long press to remove a WC bookmark is less obvious that tapping the bookmark button. It would be easier too maintain and remove some code.

**Comment by aagam-shah** [comment]
We don't remove bookmark frequently compared to adding a bookmark and so I didn't use upcoming card. But still we can change in order to have ease for users.

**Comment by maxme** [comment]
> We don't remove bookmark frequently compared to adding a bookmark and so I didn't use upcoming card. But still we can change in order to have ease for users.

I think it makes more sense to have the same card view for the 3 tabs, so let's change that.

**Comment by aagam-shah** [comment]
@maxme : Changed as per the discussion :)

**Comment by maxme** [comment]
@aagam-shah merged thanks, I also changed bookmark icon position.

**Pull request merged**
